name: Build Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-docker-images:
    name: Build & deploy docker images in GitHub registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      # -
      #   name: Login to GitHub Packages Docker Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.pkg.github.com
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      #     # username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     # password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com/toofff/bolt-docker
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: toofff/bolt-docker:${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
