# name: Continuous Integration

# on: [push, pull_request]

# jobs:
#   lint:
#     name: Lint Dockerfile
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/checkout@master
#     - name: Lint
#       uses: luke142367/Docker-Lint-Action@v1.1.1
#       with:
#         target: Dockerfile
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
